spring:
  application:
    name: dynamic-document-excel
  main:
    banner-mode: off
    web-application-type: servlet

  datasource:
    url: jdbc:postgresql://localhost:5432/document
    username: postgres
    password: 2030306
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
#        dialect: org.hibernate.dialect.PostgreSQLDialect




